### ISSUE TITLE
no function clause matching in AshAdmin.PageLive.handle_event/3 

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_admin#58]
**Describe the bug**

Liveview crashes when editing the tenant

```
** (FunctionClauseError) no function clause matching in AshAdmin.PageLive.handle_event/3
    (ash_admin 0.9.0) lib/ash_admin/pages/page_live.ex:284: AshAdmin.PageLive.handle_event("stop_editing_tenant", %{"value" => ""},
```

**Runtime**
 - Ash Admin 0.9.0

**Comment by zachdaniel** [comment]
Can you try `main`? Thanks!

**Comment by rgraff** [comment]
Still getting the same error

```elixir
error] GenServer #PID<0.949.0> terminating
** (FunctionClauseError) no function clause matching in AshAdmin.PageLive.handle_event/3
    (ash_admin 0.9.0) lib/ash_admin/pages/page_live.ex:284: AshAdmin.PageLive.handle_event("stop_editing_tenant", %{"value" => ""}, #Phoenix.LiveView.Socket<id: "phx-F3auQXR9DPpuhgHB", endpoint: KickplanWeb.Endpoint, view: AshAdmin.PageLive, parent_pid: nil, root_pid: #PID<0.949.0>, router: KickplanWeb.Router, assigns: %{__changed__: %{}, action: nil, action_type: nil, actor: nil, actor_api: nil, actor_paused: true, actor_resources: [], api: Kickplan.Organizations, apis: [Kickplan.Organizations, Kickplan.Users, Kickplan.Environments], authorizing: false, flash: %{}, id: nil, live_action: :page, params: %{"route" => []}, polymorphic_actions: nil, prefix: "/admin", primary_key: nil, record: nil, resource: Kickplan.Organizations.Organization, tab: nil, table: nil, tables: [], tenant: nil, url_path: "/admin"}, transport_pid: #PID<0.937.0>, ...>)
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:401: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /workspace/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:221: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F3auQXR9DPpuhgHB", event: "event", payload: %{"event" => "stop_editing_tenant", "type" => "click", "value" => %{"value" => ""}}, ref: "7", join_ref: "4"}
```

**Comment by zachdaniel** [comment]
missed one, sorry :)

**Comment by zachdaniel** [comment]
Just pushed a fix

**Comment by rgraff** [comment]
did you push to main or a branch?

**Comment by zachdaniel** [comment]
Pretty sure I pushed it to `main`. Make sure to use `mix deps.update` to have it use the new ref if you were already on `main`

**Comment by zachdaniel** [comment]
Sorry, my fault. I hadn't pushed. Should be fixed now.

**Comment by rgraff** [comment]
Made it past editing the tenant. Now it errors on submit.

```elixir
[error] GenServer #PID<0.1342.0> terminating
** (FunctionClauseError) no function clause matching in AshAdmin.Components.TopNav.TenantForm.handle_event/3
    (ash_admin 0.9.0) lib/ash_admin/components/top_nav/tenant_form.ex:69: AshAdmin.Components.TopNav.TenantForm.handle_event("set_tenant", %{"tenant" => "a3ed74bb-a748-416f-b8e6-740e1fa6596f"}, #Phoenix.LiveView.Socket<id: "phx-F3bQsM5Q5J_eoUXC", endpoint: KickplanWeb.Endpoint, view: AshAdmin.PageLive, parent_pid: nil, root_pid: #PID<0.1342.0>, router: KickplanWeb.Router, assigns: %{__changed__: %{}, clear_tenant: "clear_tenant", editing_tenant: false, flash: %{}, id: "tenant_editor", myself: %Phoenix.LiveComponent.CID{cid: 7}, set_tenant: "set_tenant", tenant: nil}, transport_pid: #PID<0.1330.0>, ...>)
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:630: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /workspace/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I forked the repo to see if I could patch but I'm not familiar enough with phx-target

**Comment by zachdaniel** [comment]
Sorry, lol. I did one too many and one not enough. Will fix.

**Comment by zachdaniel** [comment]
okay, try again.

**Comment by rgraff** [comment]
Still getting the same error. I can't figure it out either locally.

```elixir
[error] GenServer #PID<0.1318.0> terminating
** (FunctionClauseError) no function clause matching in AshAdmin.Components.TopNav.TenantForm.handle_event/3
    (ash_admin 0.9.0) lib/ash_admin/components/top_nav/tenant_form.ex:69: AshAdmin.Components.TopNav.TenantForm.handle_event("set_tenant", %{"tenant" => "a3ed74bb-a748-416f-b8e6-740e1fa6596f"}, #Phoenix.LiveView.Socket<id: "phx-F3bVDbCpcuiUEQzB", endpoint: KickplanWeb.Endpoint, view: AshAdmin.PageLive, parent_pid: nil, root_pid: #PID<0.1318.0>, router: KickplanWeb.Router, assigns: %{__changed__: %{}, clear_tenant: "clear_tenant", editing_tenant: false, flash: %{}, id: "tenant_editor", myself: %Phoenix.LiveComponent.CID{cid: 7}, set_tenant: "set_tenant", tenant: nil}, transport_pid: #PID<0.1306.0>, ...>)
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:630: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /workspace/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by zachdaniel** [comment]
Hm....I just tested the main branch myself and it works...

**Comment by rgraff** [comment]
I'll continue to debug...

**Comment by zachdaniel** [comment]
Maybe you're still pointing at your local version?

**Comment by rgraff** [comment]
Yes. I wasn't updating to the latest commit.

TIL: Running `mix deps.update ash_admin` will only update to the latest commit if you are using `branch: "main"`. I had `ref: "main"` and so it wasn't picking up the latest commits.

**Comment by rgraff** [comment]
And now I'm having the same issue with the clear_tenant handler.

```
** (FunctionClauseError) no function clause matching in AshAdmin.Components.TopNav.TenantForm.handle_event/3
    (ash_admin 0.9.0) lib/ash_admin/components/top_nav/tenant_form.ex:64: AshAdmin.Components.TopNav.TenantForm.handle_event("clear_tenant", %{"value" => ""}, #Phoenix.LiveView.Socket<id: "phx-F3emZ3S9a1WwtztB", endpoint: KickplanWeb.Endpoint, view: AshAdmin.PageLive, parent_pid: nil, root_pid: #PID<0.3315.0>, router: KickplanWeb.Router, assigns: %{__changed__: %{}, clear_tenant: "clear_tenant", editing_tenant: true, flash: %{}, id: "tenant_editor", myself: %Phoenix.LiveComponent.CID{cid: 7}, set_tenant: "set_tenant", tenant: "a3ed74bb-a748-416f-b8e6-740e1fa6596f"}, transport_pid: #PID<0.3303.0>, ...>)
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:630: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /workspace/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by rgraff** [comment]
I put a PR to the crash above, but with that fix I'm now experiencing another issue. I can set the tenant and actor, however, I periodically lose state and the actor (or tenant) disappears. It may also come back as a previous value.

**Comment by zachdaniel** [comment]
merged your PR, working on the rest.
